export enum ISaltDogPluginMessageType {
    PLUGINHOST_INVOKE = 'PLUGINHOST_INVOKE',
    PLUGINHOST_INVOKE_CALLBACK = 'PLUGINHOST_INVOKE_CALLBACK',
    HOST_EVENT = 'HOST_EVENT',
    PLUGINWEBVIEW_INVOKE = 'PLUGINWEBVIEW_INVOKE',
    PLUGINWEBVIEW_INVOKE_CALLBACK = 'PLUGINWEBVIEW_INVOKE_CALLBACK',
}
